### ISSUE TITLE
Missing PR number in output

### ISSUE THREAD

**Issue by leettaylor** [kyanny/gh-pr-draft#1]
When running `gh pr-draft` without a PR number it doesn't show a PR number in the output.

```
> gh pr-draft
Pull request # is marked as "draft"
```

---

Would maybe doing this sort it...

```
if [[ $# -eq 0 ]]; then
  id=$(gh pr view --json id -q '.id')
  number=$(gh pr view --json number -q '.number')
else
```

**Comment by kyanny** [comment]
Hi @leettaylor thank you for reporting the bug and providing the patch!
I've fixed the bug on #2 and released [v2.2.0](https://github.com/kyanny/gh-pr-draft/releases/tag/v2.2.0).
