### ISSUE TITLE
Use in Github Actions not working

### ISSUE THREAD

**Issue by jaredvivints** [kyanny/gh-pr-draft#3]
Hi, wondering if I could get some direction on using this in github actions. Getting the below error.

  gh auth status   
  gh pr view ${ISSUE} -R ${OWNER}/${REPO}
  gh extension install kyanny/gh-pr-draft
  gh pr checkout ${ISSUE} -R ${OWNER}/${REPO}
  gh pr-draft
  shell: /usr/bin/bash -e {0}
  env:
    CURL_URL: ***/rest/api/2/issue
    GITHUB_TOKEN: ***
    ISSUE: https://github.com/SunRun/sunrun-bi-dbt/pull/458
    OWNER: SunRun
    REPO: sunrun-bi-dbt
github.com
  ✓ Logged in to github.com as jaredvivints (GITHUB_TOKEN)
  ✓ Git operations for github.com configured to use https protocol.
  ✓ Token: *******************
  
title:	#####-4474
state:	OPEN
author:	jaredvivints
labels:	
assignees:	
reviewers:	
projects:	
milestone:	
number:	458
url:	https://github.com/SunRun/sunrun-bi-dbt/pull/458
additions:	318
deletions:	4
--
version 2 of testing this github action
Cloning into '/home/runner/.local/share/gh/extensions/gh-pr-draft'...
fatal: not a git repository (or any of the parent directories): .git
/usr/bin/git: exit status 128
Error: Process completed with exit code 1.

**Comment by kyanny** [comment]
Hi @jaredvivints thank you for the report.

It looks like an (temporary) error of `git clone` command. I think it doesn't relate to `gh-pr-draft` extension itself.
Does the error persist in your environment? Can you rerun the workflow?

**Comment by jaredvivints** [comment]
@kyanny Yes, thanks for getting back so quickly. Yes, everytime I run this I get the same response.

**Comment by kyanny** [comment]
@jaredvivints I see. Can you share the entire workflow file? You can mask any sensitive data.

**Comment by jaredvivints** [comment]
Finally got this working.
