### ISSUE TITLE
Permission denied when converting to draft

### ISSUE THREAD

**Issue by Jeff-Walker** [kyanny/gh-pr-draft#5]
Maybe just a question, but I tried this but can't get it to work. Says I don't have permission to update the PR but it doesn't say how to fix this. I can't find any OAuth2 scopes that seem relevant. I'm sure I'm missing something.

```
❯ gh pr status

Relevant pull requests in Jeff-Walker/.....

Current branch
  #3  test [test]

Created by you
  #3  test [test]

Requesting a code review from you
  You have no pull requests to review

❯ gh pr-draft 3
gh: Jeff-Walker does not have permission to convert the pull request PR_kwDOGsTjSc40QvjS to draft.
```

**Comment by kyanny** [comment]
Hi @Jeff-Walker 

Suppose you ran `gh pr-draft` in your *private* repository?

As described in [this document](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request), the draft pull request is not available with a private repository belong to a personal account.

**Comment by Jeff-Walker** [comment]
Ok, fair enough. I was using a personal, private repo to test. Thanks for the help.
